### ISSUE TITLE
Special characters are not being replaced

### ISSUE THREAD

**Issue by bmikol** [avdgaag/typogruby#27]
When running a text file containing special characters through typogruby, said characters are not being replaced with their HTML entity counterparts.

Ruby v2.2.4p230
Typogruby v.1.0.18

## Steps to Repro

1. echo "Glögg Olé søster" >> ~/foo.txt
2. typogruby ~/foo.txt

## Expected Result

`Gl&ouml;gg Ol&eacute;&nbsp;s&oslash;ster`

## Actual Result

`Glögg Olé&nbsp;søster`

**Comment by avdgaag** [comment]
Interesting. I guess we can update [characters.txt](https://github.com/avdgaag/typogruby/blob/master/lib/characters.txt) for that. Would you care to create a PR?

**Comment by bmikol** [comment]
Sorry I've been MIA - life got in the way. 

My ruby skills are still pretty novice, but I've been investigating and playing with the source trying to figure out the root of the problem before creating a PR. Turns out passing the -n argument _does_ work:

```shell
typogruby -n ~/foo.txt
> Gl&ouml;gg Ol&eacute; s&oslash;ster
```

In looking at the source, the improve(text) function is indeed missing the call to the entities(text) function. Put that in, along with adding a exclude_sensitive_tags block to entities(text) so the first fix would stop breaking the exclude tags tests.

Just created the PR.

**Comment by avdgaag** [comment]
This is replaced with #28.
